config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users#, controllers: {
    # registrations: 'users/registrations',
  #   sessions: 'users/sessions',
  #   passwords: 'users/passwords'
  # }

  devise_for :admin#, controllers: {
  #   registrations: 'admin/registrations',
  #   sessions: 'admin/sessions'
  # }
  namespace :admin do
    resources :users
    resources :events, only: %i[index destroy]
  end

  root to: 'users#top'
  get 'users/about', to: 'users#about'
  get 'events/search', to: 'events#search_index'
  get 'events/pickup', to: 'events#pickup'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :notifications do
    collection do
      patch :read
    end
  end

  post 'events/confirm', to: 'events#confirm'
  post '/events/:event_id/likes' => 'likes#create'
  delete '/events/:event_id/likes' => 'likes#destroy'
  post '/events/:event_id/join_users' => 'join_users#create'
  delete '/events/:event_id/join_users' => 'join_users#destroy'
  resources :events do
    resource :comments, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :event, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  def read
    current_user.passive_notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<div class="col-11 mx-auto">
	<div class="form_inline">
		<span>
			<%= link_to user_path(visitor) do %>
			<%= visitor.username %>
			<% end %>
			さんが
		</span><br>

		<% case notification.action %>
		<% when 'follow' then %>
			あなたをフォローしました
		<% when 'like' then %>
			<%= link_to "あなたのボランティア", notification.event, style: "font-weight: bold;"  %>にいいねしました
		<% when 'join' then %>
			<%= link_to "あなたのボランティア", notification.event, style: "font-weight: bold;"  %>に参加しました
		<% when 'comment' then %>
			<% if notification.event.user_id == visited.id %>
				<%= link_to "あなたのボランティア", notification.event, style: "font-weight: bold;" %>
			<% else %>
				<span>
					<%= link_to event_path(notification.event) do %>
					<%= notification.event.user.username %>さんの投稿
					<% end %>
				</span>
			<% end %>
			にコメントしました

			<p class="text-muted mb-0">
				<%= Comment.find_by(id: notification.comment_id)&.content %>
			</p>
		<% end %>

		<div class="small text-muted text-right">
			<%= time_ago_in_words(notification.created_at) %>前
		</div>
		<hr>

	</div>
</div>