config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users#, controllers: {
    # registrations: 'users/registrations',
  #   sessions: 'users/sessions',
  #   passwords: 'users/passwords'
  # }

  devise_for :admin#, controllers: {
  #   registrations: 'admin/registrations',
  #   sessions: 'admin/sessions'
  # }
  namespace :admin do
    resources :users
    resources :events, only: %i[index destroy]
  end

  root to: 'users#top'
  get 'users/about', to: 'users#about'
  get 'events/search', to: 'events#search_index'
  get 'events/pickup', to: 'events#pickup'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :notifications do
    collection do
      patch :read
    end
  end

  post 'events/confirm', to: 'events#confirm'
  post '/events/:event_id/likes' => 'likes#create'
  delete '/events/:event_id/likes' => 'likes#destroy'
  post '/events/:event_id/join_users' => 'join_users#create'
  delete '/events/:event_id/join_users' => 'join_users#destroy'
  resources :events do
    resource :comments, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, dependent: :destroy
  has_many :join_users, dependent: :destroy
  has_many :joined_events, through: :join_users, source: :event, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  mount_uploader :image, ImageUploader

  # 追加したカラムの新規登録のバリデーション
  validates :username,
            presence: { message: 'が入力されていません。' },
            uniqueness: { message: 'はすでに存在しています。' },
            length: { maximum: 15, minimum: 2, message: 'は2文字以上15文字以内です。' }

  validates :lastname,
            presence: { message: 'が入力されていません。' },
            length: { maximum: 10, message: 'は10文字以内です。' }

  validates :firstname,
            presence: { message: 'が入力されていません。' },
            length: { maximum: 10, message: 'は10文字以内です。' }

  validates :kana_lastname,
            presence: { message: 'が入力されていません。' },
            format: { with: /\A[\p{katakana}]+\z/, message: 'はカタカナで入力してください。' },
            length: { maximum: 10, message: 'は10文字以内です。' }

  validates :kana_firstname,
            presence: { message: 'が入力されていません。' },
            format: { with: /\A[\p{katakana}]+\z/, message: 'はカタカナで入力してください。' },
            length: { maximum: 10, message: 'は10文字以内です。' }
  # バリデーションここまで

  # ユーザーがイベントに対して、既に参加しているかどうかを判定
  def already_joined?(event)
    join_users.exists?(event_id: event.id)
  end

  # ユーザーがイベントに対して、既にいいねしているかどうかを判定
  def already_liked?(event)
    likes.exists?(event_id: event.id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def unchecked_notifications
    current_user.passive_notifications.where(checked: false)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end


end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page]).reverse_order.per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user.id), notice: 'ユーザー情報を更新しました'
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :lastname,
      :firstname,
      :kana_lastname,
      :kana_firstname,
      :image,
      :image_cache,
      :remove_image
    )
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do
      SignupMailer.send_when_signup(@user).deliver
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i[top about]

  def top; end

  def about; end

  def show
    @user = User.find(params[:id])

    @notifications = current_user.passive_notifications.page(params[:page]).per(4)

    @user_joins = @user.joined_events.page(params[:user_joins]).per(3)
    @user_hosts = @user.events.page(params[:user_hosts]).per(3)
    @user_likes = @user.liked_events.page(params[:user_likes]).per(3)

  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    user = current_user

    if user.update(user_params)
      redirect_to user_path(user.id)
    else
      @user = current_user
      render 'edit'
    end
  end

  def following
    @title = 'フォロー'
    @user  = User.find(params[:id])
    # @users = @user.following.page(params[:page]).per(5)
    # 上記ではエラーが出るので下記に変更
    @users = @user.following
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(5)
    render 'show_follow'
  end

  def followers
    @title = 'フォロワー'
    @user  = User.find(params[:id])
    @users = @user.followers
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(5)
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:username, :lastname, :firstname, :kana_lastname, :kana_firstname, :image, :image_cache, :remove_image)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def unchecked_notifications
    current_user.passive_notifications.where(checked: false)
  end
end

app/views/users/_calendar.html.erb
<%= month_calendar events: @user.joined_events do |date, events| %>
  <div class="text-left"><%= date.day %></div>
  <% events.each do |event| %>
      <a tabindex="0" class="btn btn-sm btn-outline-danger mb-1" role="button" data-toggle="popover" data-trigger="focus" title='<%= event.title %>' data-content='<%= event.start_time.strftime("%H:%M") %>から  <%= event.prefecture %><%= event.address %>'><i class="far fa-star"></i></a>
  <% end %>
<% end %>


<script>
  $("[data-toggle=popover]").popover()
</script>

app/views/users/_circle.html.erb
<div id="read">
	<% if unchecked_notifications.any? %>

		<span id="button" style="cursor: pointer">
			<i class="fab fa-envira fa-lg text-success btn btn-sm btn-outline-success">おしらせ</i>
			<i class="fas fa-flag n-flag fa-lg"></i>
		</span>

	<% else %>

			<i id="button" class="fab fa-envira fa-lg text-success btn btn-sm btn-outline-success">おしらせ</i>

	<% end %>
</div>

<!-- お知らせボタンを押した時、既読になりアイコンが消える -->
<script>
$('#read').on('click', function(){
	var $readButton = $(this);
    $.ajax({
        url:'/notifications/read',
        type:'PATCH',
    })
	// Ajaxリクエストが成功した時発動
    .done( (data) => {
        $readButton.find('.fas.fa-flag').remove()
    })
})
</script>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit "フォローする", class: "btn btn-primary mt-3" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
	<div id="follow_form">
	  <% if current_user.following?(@user) %>
	    <%= render 'unfollow' %>
	  <% else %>
	    <%= render 'follow' %>
	  <% end %>
	</div>
<% end %>

app/views/users/_notify.html.erb
<%= render @notifications %>
<%= paginate @notifications, remote: true %>

app/views/users/_stats.html.erb
<% user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(user) %>" class="btn btn-outline-info btn-sm mr-1">
      <b><%= user.following.count %></b>
    フォロー
  </a>
  <a href="<%= followers_user_path(user) %>" class="btn btn-outline-info btn-sm">
      <b><%= user.followers.count %></b>
    フォロワー
  </a>
</div>
<span class="bg-warning"><%= flash[:follow] %></span>

app/views/users/_tab_join.html.erb
<table class="table">
	  <tr><th></th><th>日時</th></tr>
	<% user_joins.each do |event| %>
	  <tr><td><%= link_to event.title, event %></td><td><%= event.start_time.strftime("%Y年%m月%d日") %></td></tr>

	<% end %>
</table>
<%= paginate user_joins, :param_name => 'user_joins', remote: true %>

app/views/users/_tab_like.html.erb
<table class="table">
	  <tr><th></th><th>日時</th></tr>
	<% user_likes.each do |event| %>
	  <tr><td><%= link_to event.title, event %></td><td><%= event.start_time.strftime("%Y年%m月%d日") %></td></tr>

	<% end %>
</table>
<%= paginate user_likes, :param_name => 'user_likes', remote: true %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォローを外す", class: "btn btn-secondary mt-3" %>
<% end %>

app/views/users/about.html.erb
<h4 class="text-center mb-4">Volun-Tunerってどんなサイト？</h4>

<hr>


<h5 class="text-center mt-3">ボランティアを...</h5>


<div class="row justify-content-center">
	<div class="card col-md-12 col-lg-5 mb-3 mr-2">
		<div class="card-body text-center">
			<h5><span class="bg-info px-2 py-2 rounded text-white">参加</span></h5>

		<img src="<%= asset_path "bokin.jpg" %>" class="img-fluid shadow rounded img-thumbnail w-75 mt-3" alt="bokin">

		</div>
	</div>

	<div class="card col-md-12 col-lg-5 mb-3">
		<div class="card-body text-center">
			<h5><span class="bg-success px-2 py-2 rounded text-white">主催</span></h5>

			<img src="<%= asset_path "heart.jpg" %>" class="img-fluid shadow rounded img-thumbnail mt-3" style="width: 60%;" alt="ハート">
		</div>
	</div>
</div>

<h5 class="text-center">できる！</h5>

<hr>


<h5 class="text-center my-5"><span class="bg-danger px-2 py-1 rounded text-white">ポイント</span></h5>

<div class="row justify-content-center">

	<div class="card col-md-12 col-lg-4 mr-3 mb-5">
		<div class="card-body text-center">
			<h5><span class="bg-secondary text-white px-2 py-1">豊富な検索機能</span></h5>

			<p>
				新着順<br>
				フリーワード<br>
				現在地<br>
				カテゴリータグで<br>
				エリア<br>
				カレンダーから<br>
				ランキングから<br>
				フォロワーから<br>
			</p>

			<p class="text-right">探すことができるよ</p>
		</div>
	</div>


	<div class="card col-md-12 col-lg-6 mr-3 mb-5">
		<div class="card-body text-center">
			<h5><span class="bg-secondary text-white px-2 py-1">ボランティアを通して繋がりができる</span></h5>

			<p class="text-left ml-5 mt-4">ボランティアへの</p>

			いいね<br>
			コメント<br>
			他のユーザーのフォロー<br>
			などの機能で

			<p>ボランティアで繋がりが出来るよ</p>
		</div>
	</div>


	<div class="card col-md-12 col-lg-5 mr-3 mb-5">
		<div class="card-body text-center">
			<h5><span class="bg-secondary text-white px-2 py-1">ボタン一つで気軽に参加</span></h5>

			<p class="mt-4">会社帰りや学校帰り、ちょっとした隙間時間に...<br>空いた時間を有効活用して社会貢献しよう</p>
		</div>
	</div>


	<div class="card col-md-12 col-lg-5 mr-3 mb-5">
		<div class="card-body text-center">
			<h5><span class="bg-secondary text-white px-2 py-1">主催も簡単</span></h5>

			<p class="mt-4">
				必要な項目を入力すれば<br>
				簡単にボランティアが主催できます<br>
				みんなで参加できて役に立つボランティアを主催してみよう<br>
			</p>
		</div>
	</div>
</div>


<hr>


<div class="row justify-content-center my-5">
	<div class="card col-10">
		<div class="card-body text-center mt-3">
			<h5 class="mb-4"><span class="bg-info text-white px-3 py-2 rounded-pill">会員登録すると...</span></h5>


			ボランティアの参加<br>
			ボランティアの主催<br>
			いいね<br>
			コメント<br>
			他のユーザーのフォロー<br>

			<p class="text-right">などが出来るようになるよ！</p>

		</div>
	</div>
</div>

<hr>

<div class="text-center">
	<%= link_to "会員登録はこちらから", new_user_registration_path, class: "btn btn-lg btn-warning shadow rounded" %>
</div>

app/views/users/edit.html.erb
<div class="align mt-4">
	<div class="grid">

		<div id="login">

			<h4><span class="fas fa-user-edit"></span>編集する</h4>

			<%= form_for(@user) do |f| %>

			<fieldset>


				<p><%= f.label :username, "ユーザーネーム" %></p>
				<p><%= f.text_field :username %></p><hr>

				<div class="row mb-3">
					<div class="col-6">
						<p><%= f.label :lastname, "姓" %></p>
						<p><%= f.text_field :lastname %></p>
					</div>
					<div class="col-6">
						<p><%= f.label :firstname, "名" %></p>
						<p><%= f.text_field :firstname %></p>
					</div>
				</div>

				<hr>

				<div class="row mb-3">
					<div class="col-6">
						<p><%= f.label :kana_lastname, "カナ姓" %></p>
						<p><%= f.text_field :kana_lastname %></p>
					</div>

					<div class="col-6">
						<p><%= f.label :kana_firstname, "カナ名" %></p>
						<p><%= f.text_field :kana_firstname %></p>
					</div>
				</div>

				<hr>

				<p><%= f.label :image, "画像" %></p>
				<p><%= f.file_field :image, id: :user_image %></p>
				<!-- 画像プレビューを表示 -->
				<%= image_tag @user.image.url, width: 100, id: :image_prev, class: "rounded-circle mt-2" %>
				　<p><%= f.check_box :remove_image %>画像を削除する</p><hr>


				<p><%= f.submit "更新" %></p>

			</fieldset>

			<% end %>

		</div> <!-- end login -->

	</div>
</div>





<!-- 画像のプレビュー機能 -->
<script type="text/javascript">
$(function() {
 function readURL(input) {
   if (input.files && input.files[0]) {
     var reader = new FileReader();
     reader.onload = function (e) {
       $('#image_prev').attr('src', e.target.result);
     }
     reader.readAsDataURL(input.files[0]);
   }
 }
 $("#user_image").change(function(){
   readURL(this);
 });
});
</script>

app/views/users/show.html.erb
<!-- スライドメニュー部分-->
<nav id="slide_menu">
	<div style="padding-top: 70px;">
		<div class="text-right mr-3"><i id="close-button" class="far fa-times-circle fa-lg text-secondary"></i></div>
		<!-- 自分の投稿に対するいいね、コメントは通知に表示しない -->
		<% notifications = @notifications.where.not(visitor_id: current_user.id) %>
		<% if notifications.exists? %>
			<div class="paginate">
				<%= render 'notify' %>
			</div>
		<% else %>
		<div class="text-center">
			<span class="px-3 text-white bg-success">通知はありません</span>
		</div>
		<% end %>
	</div>
</nav><!-- スライドメニューここまで-->

<div class="row justify-content-center">
	<div class="col-lg-5">
		<div class="row justify-content-center">
			<div class="col-md-10 mt-3 mb-3 card shadow img-thumbnail">
				<%= image_tag @user.image_url, width: 100, class: "rounded-circle mx-auto mt-4" %>
				<div class="card-body px-2 py-3 text-center">
				<h5 class="card-title"><%= @user.username %></h5>

				<!-- 本人の場合のみ通知へのリンクを表示 -->
				<% if @user == current_user %>
					<%= render 'circle' %>
				<% end %>

				<hr>
				<div class="mb-3">
					<!-- フォロー機能 -->
						<!-- フォロー、フォロワー数を表示 -->
						<div id="stats">
							<%= render 'stats', user: @user %>
						</div>

						<!-- フォローボタンの表示 -->
						<%= render 'follow_form', cached: true if user_signed_in? %>
					<!-- フォロー機能ここまで -->
				</div>
				<!-- 本人の場合のみボタンを表示 -->
				<% if @user == current_user %>
					<%= link_to "ユーザー情報編集", edit_user_path(current_user.id), class: "btn btn-outline-primary btn-sm mb-2" %><br>
					<%= link_to new_event_path, class: "btn btn-success btn-sm" do %>
						<i class="fas fa-hand-holding-heart mr-2"></i>ボランティアを主催する
					<% end %>
				<% end %>

				</div><!-- /.card-body -->
			</div><!-- /.card -->



			<div class="col-md-10 card shadow card-body mt-3 pb-5">
				<nav>
				  <div class="nav nav-tabs justify-content-center" id="nav-tab" role="tablist">
				    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true"><i class="fab fa-envira"></i>参加</a>
				    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false"><i class="fas fa-hand-holding-heart mr-1"></i>主催</a>
				    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false"><i class="far fa-thumbs-up"></i>いいね</a>
				  </div>
				</nav>

				<div class="tab-content mt-3" id="nav-tabContent">
				  <div class="tab-pane active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
					<!-- 参加イベントがない時は文章を表示 -->
					<% if @user.joined_events.count == 0 %>

						<p>まだ参加したボランティアはありません...。</p>

					<% else %>

						<div id="tab_joins">
							<%= render 'tab_join', user_joins: @user_joins %>
						</div>

					<% end %>

				  </div>

				  <div class="tab-pane" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
					<!-- 主催イベントがない時は文章を表示 -->
					<% if @user.events.count == 0 %>

						<p>まだ主催したボランティアはありません...。</p>

					<% else %>
						<div id="tab_hosts">
							<%= render 'tab_host', user_hosts: @user_hosts %>
						</div>


					<% end %>

				  </div>

				  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
					<!-- いいねしたイベントがない時は文章を表示 -->
					<% if @user.liked_events.count == 0 %>

						<p>まだいいねしたボランティアはありません...。</p>

					<% else %>
						<div id="tab_likes">
							<%= render 'tab_like', user_likes: @user_likes %>
						</div>

					<% end %>
				  </div>
				</div>
			</div>
		</div>
	</div>


	<!-- ユーザーが参加するイベントをカレンダーに表示 -->
	<div class="col-lg-7 col-md-10 text-center mt-3">
		<div class="card shadow">
		  <div class="card-header bg-success text-white">
		    <%= @user.username %>さんの予定表
		  </div>
		  <div class="card-body">
			<div id="calendar">
				<%= render 'calendar' %>
			</div>
		  </div>
		</div>
	</div><!-- /.col-md-8 -->
	<!-- カレンダーここまで -->
</div><!-- /.row -->




<script>
$(function(){
var menu = $('#slide_menu'), // スライドインするメニューを指定
    menuBtn = $('#button, #close-button'), // メニューボタンを指定
    body = $(document.body),
    menuWidth = menu.outerWidth();

    // メニューボタンをクリックした時の動き
    menuBtn.on('click', function(){
    // body に open クラスを付与する
    body.toggleClass('open');
        if(body.hasClass('open')){
            // open クラスが body についていたらメニューをスライドインする
            body.animate({'left' : menuWidth }, 300);
            menu.animate({'left' : 0 }, 300);
        } else {
            // open クラスが body についていなかったらスライドアウトする
            menu.animate({'left' : -menuWidth }, 300);
            body.animate({'left' : 0 }, 300);

        }
    });
});

</script>

app/views/users/show.js.erb
$(".paginate").html("<%= j(render :partial => 'notify') %>");
$("#calendar").html("<%= j(render :partial => 'calendar') %>");
$("#tab_joins").html("<%= j(render :partial => 'tab_join', locals: { user_joins: @user_joins }) %>");
$("#tab_hosts").html("<%= j(render :partial => 'tab_host', locals: { user_hosts: @user_hosts }) %>");
$("#tab_likes").html("<%= j(render :partial => 'tab_like', locals: { user_likes: @user_likes }) %>");

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
	<aside class="col-md-4">
		<h4><%= @user.username %></h4>
		<%= link_to "マイページに戻る", @user %>
		<%= render 'stats' %>
	</aside>
	<div class="col-md-8">
		<h3><%= @title %></h3>
		<% if @users.any? %>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>ユーザー名</th>
					<th>主催ボランティア数</th>
					<th>参加ボランティア数</th>
				</tr>
			</thead>

			<% @users.each do |user| %>

				<tbody>
					<tr>
						<td><%= link_to user.username, user %></td>
						<td><%= user.events.count %>件</td>
						<td><%= user.joined_events.count %>件</td>
					</tr>
				</tbody>

			<% end %>
		</table>
		<%= paginate @users %>

		<% end %>
	</div>
</div>