config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users#, controllers: {
    # registrations: 'users/registrations',
  #   sessions: 'users/sessions',
  #   passwords: 'users/passwords'
  # }

  devise_for :admin#, controllers: {
  #   registrations: 'admin/registrations',
  #   sessions: 'admin/sessions'
  # }
  namespace :admin do
    resources :users
    resources :events, only: %i[index destroy]
  end

  root to: 'users#top'
  get 'users/about', to: 'users#about'
  get 'events/search', to: 'events#search_index'
  get 'events/pickup', to: 'events#pickup'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :notifications do
    collection do
      patch :read
    end
  end

  post 'events/confirm', to: 'events#confirm'
  post '/events/:event_id/likes' => 'likes#create'
  delete '/events/:event_id/likes' => 'likes#destroy'
  post '/events/:event_id/join_users' => 'join_users#create'
  delete '/events/:event_id/join_users' => 'join_users#destroy'
  resources :events do
    resource :comments, only: %i[create destroy]
  end
  resources :relationships, only: %i[create destroy]
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :user, optional: true
  has_many :join_users, dependent: :destroy
  has_many :joined_users, through: :join_users, source: :user, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  mount_uploader :image, ImageUploader
  acts_as_taggable

  geocoded_by :address
  after_validation :geocode, if: ->(obj) { obj.address_changed? }

  validates :title,
            presence: { message: 'が入力されていません。' },
            length: { maximum: 30, message: 'は30文字以内です。' }

  validates :content,
            presence: { message: 'が入力されていません。' },
            length: { maximum: 200, message: 'は200文字以内です。' }

  validates :address,
            presence: { message: 'が入力されていません。' }

  validates :prefecture,
            presence: { message: 'を選択してください。' }

  validates :tag_list,
            presence: { message: 'を一つ以上入力してください。' }

  enum prefecture: {
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47
  }

  def self.within_box(distance, latitude, longitude)
    distance = distance
    center_point = [latitude, longitude]
    box = Geocoder::Calculations.bounding_box(center_point, distance)
    within_bounding_box(box)
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and event_id = ? and action = ? ', current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        event_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_join!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and event_id = ? and action = ? ', current_user.id, user_id, id, 'join'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        event_id: id,
        visited_id: user_id,
        action: 'join'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(event_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    if temp_ids.blank?
      save_notification_comment!(current_user, comment_id, user_id)
    end
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      event_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

class Admin::EventsController < ApplicationController
	before_action :authenticate_admin!
  def index
    @events = Event.page(params[:page]).reverse_order.per(5)
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to admin_events_path, alert: 'ボランティアを削除しました'
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show search_index pickup]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @join_user = JoinUser.new
    @like = Like.new
    @comments = @event.comments
    @comment = Comment.new
  end

  def new
    @event = Event.new
  end

  def create
    event = current_user.events.build(event_params)
    if event.save
      redirect_to event_path(event.id), notice: '新しいボランティアを主催しました'
    else
      @event = event
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
    if @event.user_id != current_user.id
      redirect_to event_path(@event)
    end
  end

  def update
    event = Event.find(params[:id])

    if event.user_id != current_user.id
      redirect_to event_path(event)
    elsif event.update(event_params)
      redirect_to event_path(event), notice: 'ボランティア情報を更新しました'
    else
      @event = event
      render 'edit'
    end
  end

  def destroy
    event = Event.find(params[:id])
    if event.user_id != current_user.id
      redirect_to event_path(event)
    elsif event.destroy
      redirect_to user_path(current_user), alert: 'ボランティアを削除しました'
    end
  end

  # イベント確認画面 モーダルの確認画面に変更
  # def confirm
    # パラメータで確認画面へ
    # @event = Event.new(event_params)
    # event_paramsを書けば下記を省略できる
    # @event.title = params[:event][:title]
    # @event.content = params[:content]
    # @event.date = params[:date]
    # @event.time = params[:time]
    # @event.postal_code = params[:postal_code]
    # @event.address = params[:address]
  # end

  def search_index
    # @events = Event.search(params[:search])
    if params[:selected] == 'Title'
      # セレクトボックスがタイトルの時
      search = params[:search]
      @events = Event.page(params[:page]).where(['title LIKE ?', "%#{search}%"]).reverse_order.per(6)
    elsif params[:selected] == 'Content'
      # セレクトボックスが内容の時
      search = params[:search]
      @events = Event.page(params[:page]).where(['content LIKE ?', "%#{search}%"]).reverse_order.per(6)
    elsif params[:tag_name]
      # タグをクリックした時に同じタグ名のイベントを表示
      # 現在の日時を過ぎたイベントは表示しない
      # 日時が近い順に表示
      @events = Event.where('events.start_time > ?', DateTime.now).page(params[:page]).tagged_with(params[:tag_name].to_s).per(6)
    elsif params[:latitude]
      latitude = params[:latitude].to_f
      longitude = params[:longitude].to_f
      # 10kmは約6.21371マイル　半径10km以内のイベントを表示
      # 現在の日時を過ぎたイベントは表示しない
      # 日時が近い順に表示
      @events = Event.where('events.start_time > ?', DateTime.now).page(params[:page]).within_box(6.21371, latitude, longitude).per(6)
    elsif params[:prefecture]
      # 現在の日時を過ぎたイベントは表示しない
      # 日時が近い順に表示
      @events = Event.where('events.start_time > ?', DateTime.now).page(params[:page]).where(prefecture: params[:prefecture]).per(6)
    else
      # 新着順に全件表示
      # 現在の日時を過ぎたイベントは表示しない
      @events = Event.where('events.start_time > ?', DateTime.now).page(params[:page]).reverse_order.per(6)
    end
  end

  def pickup
    # ランダムに取得
    @event_randoms = Event.where('events.start_time > ?', DateTime.now).order('RANDOM()').limit(6)

      if user_signed_in?
        # フォローしているユーザーを取得
        follow_users = current_user.following
        # フォローユーザーのツイートを表示
        @follow_events = Event.where(user_id: follow_users).limit(6)
      end

    # いいね数ランキングの記述
    @event_like_ranking = Event.find(Like.group(:event_id).order('count(event_id) desc').limit(6).pluck(:event_id))

    # 参加人数ランキングの記述
    @event_join_ranking = Event.find(JoinUser.group(:event_id).order('count(event_id) desc').limit(6).pluck(:event_id))

    # ユーザーの参加数ランキングの記述
    @user_join_ranking = User.find(JoinUser.group(:user_id).order('count(user_id) desc').limit(9).pluck(:user_id))

    # ユーザーの主催数ランキングの記述
    @user_event_ranking = User.find(Event.group(:user_id).order('count(user_id) desc').limit(9).pluck(:user_id))
  end

  private

  def event_params
    params.require(:event).permit(:title, :content, :start_time, :prefecture, :address, :image, :image_cache, :remove_image, :tag_list, :latitude, :longitude)
  end

end

app/helpers/admin/events_helper.rb
# frozen_string_literal: true

module Admin::EventsHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_calendar_index.html.erb
<!-- イベント全てをカレンダーに表示 -->
<%= month_calendar events: @events do |date, events| %>
<div class="text-left"><%= date.day %></div>

<!-- 0件の時はボタンを表示しない -->
<% if events.count > 0 %>

<!-- モーダルボタンの設定 -->
<div class="text-center">
	<button type="button" class="calendar-modal btn btn-outline-info btn-sm p-1" data-toggle="modal" data-target="#eventModalLong-<%= date.day %>">
		<%= events.count %>件
	</button>
</div>

<% else %>

<div class="text-center calendar-modal">
	<%= events.count %>件
</div>

<% end %>

<!-- モーダルの設定 -->
<div class="modal fade" id="eventModalLong-<%= date.day %>" tabindex="-1" role="dialog" aria-labelledby="eventModalLongTitle" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="eventModalLongTitle"><%= date.day %>日のボランティア全件</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<ul>
					<% events.each do |event| %>
					<li><%= link_to event.title, event %></li>
					<% end %>
				</ul>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
			</div>
		</div>
	</div>
</div>

<% end %>
<!-- モーダル設定ここまで -->

app/views/events/_japan_map.html.erb
<div class="japan_map">
    <%= image_tag 'japan.png', class: "img", alt: "日本地図" %>
    <span class="area_btn area1" data-area="1">北海道・東北</span>
    <span class="area_btn area2" data-area="2">関東</span>
    <span class="area_btn area3" data-area="3">中部</span>
    <span class="area_btn area4" data-area="4">近畿</span>
    <span class="area_btn area5" data-area="5">中国・四国</span>
    <span class="area_btn area6" data-area="6">九州・沖縄</span>

    <div class="area_overlay"></div>
    <div class="pref_area">
        <div class="pref_list" data-list="1">
            <div data-id="1"><%= link_to "北海道", events_search_path(prefecture: 1) %></div>
            <div data-id="2"><%= link_to "青森県", events_search_path(prefecture: 2) %></div>
            <div data-id="3"><%= link_to "岩手県", events_search_path(prefecture: 3) %></div>
            <div data-id="4"><%= link_to "宮城県", events_search_path(prefecture: 4) %></div>
            <div data-id="5"><%= link_to "秋田県", events_search_path(prefecture: 5) %></div>
            <div data-id="6"><%= link_to "山形県", events_search_path(prefecture: 6) %></div>
            <div data-id="7"><%= link_to "福島県", events_search_path(prefecture: 7) %></div>
            <div></div>
        </div>

        <div class="pref_list" data-list="2">
            <div data-id="8"><%= link_to "茨城県", events_search_path(prefecture: 8) %></div>
            <div data-id="9"><%= link_to "栃木県", events_search_path(prefecture: 9) %></div>
            <div data-id="10"><%= link_to "群馬県", events_search_path(prefecture: 10) %></div>
            <div data-id="11"><%= link_to "埼玉県", events_search_path(prefecture: 11) %></div>
            <div data-id="12"><%= link_to "千葉県", events_search_path(prefecture: 12) %></div>
            <div data-id="13"><%= link_to "東京都", events_search_path(prefecture: 13) %></div>
            <div data-id="14"><%= link_to "神奈川県", events_search_path(prefecture: 14) %></div>
            <div></div>
        </div>

        <div class="pref_list" data-list="3">
            <div data-id="15"><%= link_to "新潟県", events_search_path(prefecture: 15) %></div>
            <div data-id="16"><%= link_to "富山県", events_search_path(prefecture: 16) %></div>
            <div data-id="17"><%= link_to "石川県", events_search_path(prefecture: 17) %></div>
            <div data-id="18"><%= link_to "福井県", events_search_path(prefecture: 18) %></div>
            <div data-id="19"><%= link_to "山梨県", events_search_path(prefecture: 19) %></div>
            <div data-id="20"><%= link_to "長野県", events_search_path(prefecture: 20) %></div>
            <div data-id="21"><%= link_to "岐阜県", events_search_path(prefecture: 21) %></div>
            <div data-id="22"><%= link_to "静岡県", events_search_path(prefecture: 22) %></div>
            <div data-id="23"><%= link_to "愛知県", events_search_path(prefecture: 23) %></div>
            <div></div>
        </div>

        <div class="pref_list" data-list="4">
            <div data-id="24"><%= link_to "三重県", events_search_path(prefecture: 24) %></div>
            <div data-id="25"><%= link_to "滋賀県", events_search_path(prefecture: 25) %></div>
            <div data-id="26"><%= link_to "京都府", events_search_path(prefecture: 26) %></div>
            <div data-id="27"><%= link_to "大阪府", events_search_path(prefecture: 27) %></div>
            <div data-id="28"><%= link_to "兵庫県", events_search_path(prefecture: 28) %></div>
            <div data-id="29"><%= link_to "奈良県", events_search_path(prefecture: 29) %></div>
            <div data-id="30"><%= link_to "和歌山県", events_search_path(prefecture: 30) %></div>
            <div></div>
        </div>

        <div class="pref_list" data-list="5">
            <div data-id="31"><%= link_to "鳥取県", events_search_path(prefecture: 31) %></div>
            <div data-id="32"><%= link_to "島根県", events_search_path(prefecture: 32) %></div>
            <div data-id="33"><%= link_to "岡山県", events_search_path(prefecture: 33) %></div>
            <div data-id="34"><%= link_to "広島県", events_search_path(prefecture: 34) %></div>
            <div data-id="35"><%= link_to "山口県", events_search_path(prefecture: 35) %></div>
            <div data-id="36"><%= link_to "徳島県", events_search_path(prefecture: 36) %></div>
            <div data-id="37"><%= link_to "香川県", events_search_path(prefecture: 37) %></div>
            <div data-id="38"><%= link_to "愛媛県", events_search_path(prefecture: 38) %></div>
            <div data-id="39"><%= link_to "高知県", events_search_path(prefecture: 39) %></div>
            <div></div>
        </div>

        <div class="pref_list" data-list="6">
            <div data-id="40"><%= link_to "福岡県", events_search_path(prefecture: 40) %></div>
            <div data-id="41"><%= link_to "佐賀県", events_search_path(prefecture: 41) %></div>
            <div data-id="42"><%= link_to "長崎県", events_search_path(prefecture: 42) %></div>
            <div data-id="43"><%= link_to "熊本県", events_search_path(prefecture: 43) %></div>
            <div data-id="44"><%= link_to "大分県", events_search_path(prefecture: 44) %></div>
            <div data-id="45"><%= link_to "宮崎県", events_search_path(prefecture: 45) %></div>
            <div data-id="46"><%= link_to "鹿児島県", events_search_path(prefecture: 46) %></div>
            <div data-id="47"><%= link_to "沖縄県", events_search_path(prefecture: 47) %></div>
        </div>
    </div>
</div>

app/views/events/_join_index.html.erb
参加人数: <%= event.join_users.count %><br>
<% event.joined_users.each do |user| %>
		<%= link_to user.username, user %>さん<br>
<% end %>

app/views/events/_like_index.html.erb
いいね数: <%= event.likes.count %><br>
<% event.liked_users.each do |user| %>
  <%= link_to user.username, user %>さん<br>
<% end %>

app/views/events/_tag_search.html.erb
<%= link_to "ゴミ拾い", events_search_path(tag_name: "ゴミ拾い"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "募金", events_search_path(tag_name: "募金"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "東京オリンピック", events_search_path(tag_name: "東京オリンピック"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "災害支援", events_search_path(tag_name: "災害支援"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "動物保護", events_search_path(tag_name: "動物保護"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "飢餓", events_search_path(tag_name: "飢餓"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "台風", events_search_path(tag_name: "台風"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "熊本地震", events_search_path(tag_name: "熊本地震"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "難民", events_search_path(tag_name: "難民"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "教育", events_search_path(tag_name: "教育"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "障害者", events_search_path(tag_name: "障害者"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "子供", events_search_path(tag_name: "子供"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "スポーツ", events_search_path(tag_name: "スポーツ"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "女性", events_search_path(tag_name: "女性"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "宗教", events_search_path(tag_name: "宗教"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "国際協力", events_search_path(tag_name: "国際協力"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "環境", events_search_path(tag_name: "環境"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "農業", events_search_path(tag_name: "農業"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "衛生", events_search_path(tag_name: "衛生"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "人権", events_search_path(tag_name: "人権"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "住環境", events_search_path(tag_name: "住環境"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "寄付", events_search_path(tag_name: "寄付"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "高齢者", events_search_path(tag_name: "高齢者"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "歴史", events_search_path(tag_name: "歴史"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "学習", events_search_path(tag_name: "学習"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>
<%= link_to "医療", events_search_path(tag_name: "医療"), class: "btn-sm btn-info mr-2 d-inline-block mb-3" %>

app/views/events/confirm.html.erb
 <h3>イベント確認画面</h3>

 <p>タイトル：<%= @event.title %></p>
 <p>内容：<%= @event.content %></p>
 <p>日時：<%= @event.start_time.strftime("%Y-%m-%d %H:%M") %></p>
 <p>郵便番号：<%= @event.postal_code %></p>
 <p>住所：<%= @event.address %></p>
 <p>タグ：<%= render 'events/tag_list', tag_list: @event.tag_list %></p>
 <p>画像：<%= image_tag(@event.image_url, width: 100) if @event.image? %></p>


 <%= form_for(@event, url: events_path, method: :post) do |f| %>

	 <%= f.hidden_field :title, :value => @event.title %>
	 <%= f.hidden_field :content, :value => @event.content %>
	 <%= f.hidden_field :start_time, :value => @event.start_time %>
	 <%= f.hidden_field :postal_code, :value => @event.postal_code %>
	 <%= f.hidden_field :address, :value => @event.address %>
	 <%= f.hidden_field :image, :value => @event.image %>
	 <%= f.hidden_field :tag_list, :value => @event.tag_list.join(',') %>
	 <%= f.hidden_field :latitude, :value => @event.latitude %>
	 <%= f.hidden_field :longitude, :value => @event.longitude %>

	 <%= f.submit 'ボランティアを主催する' %>
 <% end %>

app/views/events/index.html.erb
<div class="row">
	<div class="col-xs-12 col-lg-4 mb-3"><!-- 全件表示ここから -->
		<div class="card shadow text-center">
			<div class="card-header">
				新着順に全件表示
			</div>
			<div class="card-body">
				<%= link_to "ボランティアを見る", events_search_path, class: "btn btn-outline-primary shadow-sm rounded-pill" %>
			</div>
		</div>
	</div><!-- 全件表示ここまで -->

	<div class="col-xs-12 col-lg-4 d-lg-none mb-3"><!-- 現在地検索ここから -->
		<div class="card shadow text-center">
			　<div class="card-header">
				現在地から近い順に表示
			</div>

			<div class="card-body row">

				　		<button id="button" onclick="getPosition();" class="btn btn-outline-danger shadow-sm mx-auto">現在地から探す</button>

			</div>
		</div>
	</div><!-- 現在地検索ここまで -->

	<div class="col-xs-12 col-lg-8 mb-3"><!-- フリーワード検索ここから -->
		<div class="card shadow text-center">
			<div class="card-header">
				フリーワード検索
			</div>
			<div class="card-body">
				<!-- 検索フォームの表示 -->
				<%= form_with url:events_search_path, :method => 'get', local: true do |f| %>
				<%= f.select :selected, [['タイトル','Title'],['内容','Content']] %>
				<%= f.search_field :search, :size=>"40", class: "search_box border shadow-sm" %>
				<%= f.submit '検索する', name: nil, class: "btn btn-outline-dark btn-sm shadow-sm" %>
				<% end %>
				<!-- ここまで -->
			</div>
		</div>
	</div><!-- フリーワード検索ここまで -->

	<hr>



	<div class="col-xs-12 col-lg-12 mb-3"><!-- タグ検索ここから -->
		<div class="card shadow text-center">
			<div class="card-header">
				タグで検索
			</div>
			<div class="card-body">
				<div class="row justify-content-center mb-2">
					<div class="col-10">
						<%= render 'tag_search' %>
					</div>
				</div>

			</div>
		</div>
	</div><!-- タグ検索ここまで -->


	<hr>


	<div class="col-xs-12 col-lg-6 mb-3"><!-- カレンダーここから -->
		<div class="card shadow text-center">
			<div class="card-header">
				カレンダー
			</div>
			<div class="card-body">
				<div id="calendar">
					<%= render 'calendar_index' %>
				</div>

			</div>
		</div>
	</div><!-- カレンダーここまで -->

	<div class="col-xs-12 col-lg-6"><!-- エリア検索ここから -->
		<div class="card shadow text-center">
			<div class="card-header">
				エリアで探す
			</div>
			<div class="card-body">

				<%= render 'japan_map' %>

			</div>
		</div>
	</div><!-- エリア検索ここまで -->
</div>











<!-- エリア選択の記述 -->
<script>
	$(function(){
    //地域を選択
    $('.area_btn').click(function(){
    	$('.area_overlay').show();
    	$('.pref_area').show();
    	var area = $(this).data('area');
    	$('[data-list]').hide();
    	$('[data-list="' + area + '"]').show();
    });

    //レイヤーをタップ
    $('.area_overlay').click(function(){
    	prefReset();
    });

    //都道府県をクリック
    $('.pref_list [data-id]').click(function(){
    	if($(this).data('id')){
    		var id = $(this).data('id');
            //このidを使用して行いたい操作をしてください
            //都道府県IDに応じて別ページに飛ばしたい場合はこんな風に書く↓
            //window.location.href = 'https://kinocolog.com/pref/' + id;

            prefReset();
        }
    });

    //表示リセット
    function prefReset(){
    	$('[data-list]').hide();
    	$('.pref_area').hide();
    	$('.area_overlay').hide();
    }
});
</script>




<!-- 現在地検索の記述 -->
<script>
    // 現在地取得処理
    function getPosition() {
      // 現在地を取得
      navigator.geolocation.getCurrentPosition(
        // 取得成功した場合
        function(position) {
        	window.location.href = "/events/search?latitude="+position.coords.latitude+"&longitude="+position.coords.longitude
            // $.ajax({
            //   url: "/events/search_location",
            //   type: "GET",
            //   dataType: 'html',
            //   data: {latitude : position.coords.latitude,
            //         longitude : position.coords.longitude},
            // });
        },
        // 取得失敗した場合
        function(error) {
        	switch(error.code) {
            case 1: //PERMISSION_DENIED
            alert("位置情報の利用が許可されていません");
            break;
            case 2: //POSITION_UNAVAILABLE
            alert("現在位置が取得できませんでした");
            break;
            case 3: //TIMEOUT
            alert("タイムアウトになりました");
            break;
            default:
            alert("その他のエラー(エラーコード:"+error.code+")");
            break;
        }
    }
    );
  }
</script>

app/views/events/search_index.js.erb
$("#paginate").html("<%= j(render :partial => 'search_index', locals: { events: @events }) %>");